### PR TITLE
fix crash and imrove startup time

### PR DESCRIPTION
**Pull request by psifidotos**
--fix crash because the repeater can not catch up
with the model changes during startup
--this also improves a lot the start up loading as
the visuals are painted only when the component
has completed its initialization phase

### CODE REVIEW

**Comment by psifidotos** [comment]
this was reported by a user of Latte Dock at: https://github.com/psifidotos/Latte-Dock/issues/143#issuecomment-278121690

**Comment by kupiqu** [comment]
This pull request fixes issue #14 
I hope the pull request is accepted.

**Comment by kotelnik** [comment]
Many thanks for finding the issue and fixing my code! :)

**Comment by psifidotos** [comment]
my pleasure to have helped ;)

**Pull request merged**
